# Generated by Django 5.1.2 on 2024-10-21 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('iscustom', models.BooleanField()),
                ('fingerposition1', models.IntegerField()),
                ('fingerposition2', models.IntegerField()),
                ('fingerposition3', models.IntegerField()),
                ('fingerposition4', models.IntegerField()),
                ('fingerposition5', models.IntegerField()),
                ('fingerposition6', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongChord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('length', models.IntegerField()),
                ('chord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songchords', to='musicwebsite.chord')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songchords', to='musicwebsite.song')),
            ],
        ),
    ]
