# Generated by Django 5.1.2 on 2024-10-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chord',
            old_name='fingerposition1',
            new_name='base',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='fingerposition2',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='fingerposition3',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='fingerposition4',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='fingerposition5',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='fingerposition6',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='iscustom',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='rootname',
        ),
        migrations.AddField(
            model_name='chord',
            name='fingers',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chord',
            name='frets',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
