# Generated by Django 5.1.2 on 2024-11-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0003_alter_chord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='isCustom',
            field=models.BooleanField(db_default=False),
        ),
    ]
