# Generated by Django 5.1.2 on 2024-11-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0004_chord_iscustom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='song',
            name='updated_at',
        ),
    ]
