# Generated by Django 5.1.2 on 2024-11-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0005_chord_image'),
        ('musicwebsite', '0005_remove_song_created_at_remove_song_updated_at'),
    ]

    operations = [
    ]
