# Generated by Django 5.1.2 on 2024-12-02 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0006_merge_20241127_1616'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songchord',
            name='chord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicwebsite.chord'),
        ),
        migrations.AlterField(
            model_name='songchord',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicwebsite.song'),
        ),
    ]
